import type { Metadata } from "next";
import { Montserrat, Raleway } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import AuthProvider from "@/Providers/AuthProvider";
import ReactQueryProvider from "@/Providers/ReactQueryProvider";

const raleway = Raleway({ subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], variable: "--raleway" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <ReactQueryProvider>
        <AuthProvider>
          <Toaster />
          {children}
        </AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
